SOURCES = checker.c
SOURCES += stack.c
SOURCES += stack2.c
SOURCES += operations.c
SOURCES += atoi_stat.c
SOURCES += print.c
SOURCES += message.c
SOURCES += duplicate_check.c
SOURCES += merge_sort.c
SOURCES += join_del.c
SOURCES += parsing.c

OBJECTS = $(SOURCES:.c=.o)

NAME = checker

all: $(NAME)

$(NAME):
	@gcc -c -Wall -Wextra -Werror checker.c
	@gcc -o $(NAME) -Wall -Wextra -Werror $(SOURCES) -L. libft.a

clean:
	@rm -f checker.o
	
fclean: clean
	@rm -f $(NAME)

re: fclean all
