all:
	@make -f Makefile.checker
	@make -f Makefile.push_swap

clean:
	@make clean -f Makefile.checker
	@make clean -f Makefile.push_swap

fclean:
	@make fclean -f Makefile.checker
	@make fclean -f Makefile.push_swap

re: fclean
	@make re -f Makefile.checker
	@make re -f Makefile.push_swap